### PR TITLE
Add module to exfiltrate files and data to a GitHub repository

### PR DESCRIPTION
**Pull request by nnh100**
Hi, sorry for all the messed up pull requests (doing this for the first time on GitHub). I wrote this module to exfiltrate files to github as part of a project at work. Please do let me know if it needs improvement.

thanks,
Nga

### CODE REVIEW

**Comment by benichmt1** [comment]
Very cool PR!

**Comment by nnh100** [comment]
Thanks! I did think if at least one person appreciates it, it was worth it!

**Comment by rvrsh3ll** [comment]
nnh100, nice PR! Can you switch this to the 2.0_beta branch please?

**Comment by nnh100** [comment]
rvrsh3ll - awesome. I have updated and tested so hopefully it should work. Let me know if not as I'm not so sure about the branch-switching stuff.

**Comment by void-in** [comment]
@nnh100 Nice module. Shouldn't this is ```OfsecSafe : False``` since it is exfiltering the files saved on disk and therefore leaving forensic artifacts and changing the access times of those files?

**Comment by nnh100** [comment]
void-in - good question..  from my testing the accessed date of files is not changed as a result of the PS script (I also cheated and looked at what another directory enumeration PR had this set to). However, whether or not the calls to Get-Content/Get-ChildItem/Invoke-RestMethod leaves any trace of disk artifacts I would say probably not but I'm not certain (if anyone knows feel free to correct). 

Also the option to exfil data to a file allows the user to execute arbitrary PS commands so it could in theory touch disk but that would be beyond the control of the module itself.

**Comment by rvrsh3ll** [comment]
Anything special I should know when running this? I'm attempting to use it but, nothing is uploaded.

**Comment by nnh100** [comment]
Well, there are a few caveats but this was just a case of an awful cut n paste job. I've removed the offending lines at the bottom of the PS script and retested.  There is a walkthrough doc if needed.  

On the caveats you need to make sure the Personal Access Token is base64 encoded and if you're doing file uploads you do have to specify the GitHub file path (GHFilePath, meaning you can't upload to the root folder). At the moment you can't specify a branch either (hardcoded to master for now). Also PS v3. 

I wasn't sure how to handle the 'Required' field for parameter sets. So for example 'GHFileName' and 'Data' are both required if doing data upload, and for file uploads 'GHFilePath', 'LocalFilePath' are both required, but I can't set these as 'Required:True' because they must be used separately. 

If it's too much hassle feel free to ignore this PR!

**Comment by rvrsh3ll** [comment]
Thanks! That did it. Great stuff. Merging!

**Comment by nnh100** [comment]
np, this was fun. Keep up the good work, really cool tool Empire is.

**Pull request merged**
